language: php
php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
  - hhvm

cache:
  directories:
    - vendor

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit

notifications:
  on_success: never
  on_failure: always
