language: php
php:
  - "7.3"
  - "7.4"

cache:
  directories:
    - vendor

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit

notifications:
  on_success: never
  on_failure: always
